#ifndef MEMORY_H
#define MEMORY_H

#include "../core/types.h"

/* TODO: Document */

// Size of memory
#define MEMORY_SIZE 0xffff

// $FFFF	Interrupt Enable Flag
#define MEMORY_INTERRUPT_ENABLE_FLAG 0xffff

// $FF80-$FFFE	Zero Page - 127 bytes
#define MEMORY_ZERO_PAGE_LOWER 0xff80
#define MEMORY_ZERO_PAGE_UPPER 0xfffe

// $FF00-$FF7F	Hardware I/O Registers
#define MEMORY_HARDWARE_IO_REGISTERS_LOWER 0xff00
#define MEMORY_HARDWARE_IO_REGISTERS_UPPER 0xff7f

// $FEA0-$FEFF	Unusable Memory
#define MEMORY_UNUSABLE_MEMORYORY_LOWER 0xfea0
#define MEMORY_UNUSABLE_MEMORYORY_UPPER 0xfeff

// $FE00-$FE9F	OAM - Object Attribute Memory
#define MEMORY_OBJECT_ATTRIBUTE_MEMORYORY_LOWER 0xfe00
#define MEMORY_OBJECT_ATTRIBUTE_MEMORYORY_UPPER 0xfe9f

// $E000-$FDFF	Echo RAM - Reserved, Do Not Use
#define MEMORY_ECHO_RAM_LOWER 0xe000
#define MEMORY_ECHO_RAM_UPPER 0xfdff

// $D000-$DFFF	Internal RAM - Bank 1-7 (switchable - CGB only)
#define MEMORY_INTERNAL_RAM_SWITCHABLE_LOWER 0xd000
#define MEMORY_INTERNAL_RAM_SWITCHABLE_UPPER 0xdfff

// $C000-$CFFF	Internal RAM - Bank 0 (fixed)
#define MEMORY_INTERNAL_RAM_LOWER 0xc000
#define MEMORY_INTERNAL_RAM_UPPER 0xcfff

// $A000-$BFFF	Cartridge RAM (If Available)
#define MEMORY_CARTRIDGE_RAM_LOWER 0xa000
#define MEMORY_CARTRIDGE_RAM_UPPER 0xbfff

// $9C00-$9FFF	BG Map Data 2
#define MEMORY_BG_MAP_DATA_2_LOWER 0x9c00
#define MEMORY_BG_MAP_DATA_2_UPPER 0x9fff

// $9800-$9BFF	BG Map Data 1
#define MEMORY_BG_MAP_DATA_1_LOWER 0x9800
#define MEMORY_BG_MAP_DATA_1_UPPER 0x9bff

// $8000-$97FF	Character RAM
#define MEMORY_CHARACTER_RAM_LOWER 0x8000
#define MEMORY_CHARACTER_RAM_UPPER 0x97ff

// $4000-$7FFF	Cartridge ROM - Switchable Banks 1-xx
#define MEMORY_CARTRIDGE_ROM_SWITCHABLE_LOWER 0x4000
#define MEMORY_CARTRIDGE_ROM_SWITCHABLE_UPPER 0x7fff

// $0150-$3FFF	Cartridge ROM - Bank 0 (fixed)
#define MEMORY_CARTRIDGE_ROM_LOWER 0x0150
#define MEMORY_CARTRIDGE_ROM_UPPER 0x3fff

// $0100-$014F	Cartridge Header Area
#define MEMORY_CARTRIDGE_HEADER_LOWER 0x0100
#define MEMORY_CARTRIDGE_HEADER_UPPER 0x014f

// $0000-$00FF	Restart and Interrupt Vectors
#define MEMORY_RESTART_INTERRUPT_LOWER 0x0000
#define MEMORY_RESTART_INTERRUPT_UPPER 0x00ff

typedef ubyte_t* memory_t;

#endif